event_create:
  path: /api/v1/events
  controller: App\Controller\EventController::createEvent
  methods: POST

event_list:
  path: /api/v1/events
  controller: App\Controller\EventController::getEvents
  methods: GET

event_delete:
  path: /api/v1/events/{id}
  controller: App\Controller\EventController::deleteEvent
  methods: DELETE

event_edit:
  path: /api/v1/events/{id}
  controller: App\Controller\EventController::editEvent
  methods: PUT
