event_create:
  path: /api/v1/events
  controller: App\Controller\EventController::createEvent
  methods: POST

event_list:
  path: /api/v1/events
  controller: App\Controller\EventController::getEvents
  methods: GET